services:
  - type: web
    name: ElevateTradingBot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python render_launch.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: NON_INTERACTIVE
        value: true
      - key: PORT
        value: 5000
      - key: BITGET_API_KEY
        sync: false
      - key: BITGET_API_SECRET
        sync: false
      - key: BITGET_API_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    region: oregon
    healthCheckPath: /
    healthCheckPort: 5000
    autoDeploy: true
version: "1"